name: Build Flutter Web

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --wasm

      - name: Move build to docs
        run: |
          mv build/web/ docs/

      - name: Commit report
        run: |
          git add -A
          git config --global user.name 'Felipe Passos'
          git config --global user.email 'berkspar@gmail.com'
          git commit -am "bot: automated deploy"
          git push
